url: http://catchmate.ca
title: Catchmate
email: roger@minotaursoftware.com
description: > # "Catchmate allows food processors to easily track production and label variable weight cases of product with GS1-128 case labels."
markdown: kramdown
permalink: pretty
