# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://catchmate.ca
title: Catchmate
email: roger@minotaursoftware.com
author: Catchmate by Minotaur Softgare
description: > # "Catchmate is the easiest way to case label your variable and fixed weight food items"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: 
  - title: github
    url:
  - title: linkedin
    url:
